### ISSUE TITLE
Are you working on FTE QW, too? 

### ISSUE THREAD

**Issue by ManuelKugelmann** [Shpoike/Quakespasm#10]
Someone named "Spoike" does commits there...
https://sourceforge.net/p/fteqw/activity/?page=0&limit=100#5dcd805cee24ca3d950babdd

**Comment by TheDraguun** [comment]
The readme  solved the question for me ... since you are familiar with both FTE and QS(S), any reccommendations for me: https://www.reddit.com/r/quake/comments/dxrg85/fte_or_quakespasm_mechanics_not_graphics/ ?

BTW: Thanks for putting all that work into Q1!

**Comment by Shpoike** [comment]
yes
