### ISSUE TITLE
Mod_CheckWaterVis overflow

### ISSUE THREAD

**Issue by Novum** [Shpoike/Quakespasm#106]
https://github.com/Shpoike/Quakespasm/blob/bf20203857fd0c6f964a219fd1d116896b190430/Quake/gl_model.c#L2102

This resets `i` of the outer loop which then causes `leaf++` to overflow the `loadmodel->leafs` allocation.

See https://github.com/Novum/vkQuake/commit/31829bfd025c74f05082f07b3518e835ba8b7039

**Comment by Shpoike** [comment]
fixed in 334931c65eb013b5d21f010110d12a34a298ca19
