### ISSUE TITLE
Messed up weapons in christmasjam/halloween jam

### ISSUE THREAD

**Issue by Ph0rk0z** [Shpoike/Quakespasm#11]
https://imgur.com/a/nFH5pmb

I don't know if it's a config or what. They look normal in the original game.

**Comment by Shpoike** [comment]
QSS supports replacement textures on mdls, QS does not.
Probably its picking up some badly named texture for an md3 replacement model (QSS does not fiddle with model filename extensions so if you want it to load an md3 then the filename must exactly match what the gamecode specifies).
