### ISSUE TITLE
Arcane Dimensions HUD goes off screen in 4k, spreads proportionally with resolution or scale

### ISSUE THREAD

**Issue by Macil** [Shpoike/Quakespasm#119]
I started Arcane Dimensions while running in 4k (3840x2160) and its split HUD was mostly hidden off of the sides of the screen. I found that lowering the scale option would bring the left and right HUD pieces toward the center of the screen to be no longer hidden while shrinking it, but doing that would make the HUD uncomfortably small. The only way to get the HUD to stay on screen while at a decent size was to switch to a lower resolution. Ideally I would be able to get the same HUD layout/proportions as lower resolutions by increasing the scale option, as it normally works, but in this specific case it breaks the HUD.

Here's a pair of screenshots in QSS showing the effect of changing the scale setting while at 1280x720:

![spasm0003](https://user-images.githubusercontent.com/577345/210223326-6266fb72-4e80-434c-b77a-ad5559084a5e.png)
![spasm0004](https://user-images.githubusercontent.com/577345/210223354-af4216ef-40b0-4974-a81d-5bb370138358.png)

Here's a pair of screenshots showing the difference of AD's HUD between 1920x1080 and 3840x2160. (These screenshots are actually in vkQuake because my machine with a 4k monitor is a Steam Deck that I only have vkQuake on and haven't gotten QSS running on successfully. From testing at lower resolutions on another computer, it seems VkQuake and QSS have the same behavior around this issue, besides that VkQuake automatically acts as if you changed your scale setting proportionally when you change your resolution, which is the behavior I would have done manually in this case had it been QSS.)

![20230102022043_1](https://user-images.githubusercontent.com/577345/210225546-4145a5a2-b057-4002-b187-6e5eeb47b8e1.jpg)
![20230102022109_1](https://user-images.githubusercontent.com/577345/210225561-3db79c1c-6984-4046-8848-1af6bc304280.jpg)

QSS 2022-08-11
Arcane Dimensions 1.80 patch 1
The issue also exists in vkQuake. The issue does not exist in QuakeSpasm as it doesn't support AD's custom HUD.

**Comment by Shpoike** [comment]
That is an AD bug, not the engine's. You're reporting it in the wrong place.

https://github.com/SimsOCallaghan/ArcaneDimensions/blob/master/csqc_hudad.qc#L2159
that line is the source of the bug - any reference to that 'hudscale' variable is a defect, as the hud scale is already baked into the virtual size.
you can set scr_sbarscale to a lower value to reduce the severity of the bug, but that'll of course make the hud unreadable on a high dpi screen.
