### ISSUE TITLE
Issues with continuous integration workflow

### ISSUE THREAD

**Issue by alexey-lysiuk** [Shpoike/Quakespasm#123]
Continuous integration is stuck at `Waiting for a runner to pick up this job...` because macOS 10.15 is no longer supported by [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

Update to `macos-11` would fix this problem, but another issue arises. Failed builds are marked as succeeded.
For example, the current `qsrebase` HEAD, 49822069a33ff78f7a2b8fcaa4380a549302c0de, fails with the following error.
```
/Users/runner/work/quakespasm-spiked/quakespasm-spiked/MacOSX/English.lproj/InfoPlist.strings:1:1: error: could not decode input file using specified encoding: Unicode (UTF-16), and the file contents appear to be encoded in Unicode (UTF-8) (in target 'QuakeSpasm-Spiked-SDL2' from project 'QuakeSpasm')
```
However, shell scripts do not propagate errors, i.e. there is no `errexit` option set. Red steps/jobs appear as green because of this.

**Comment by timbergeron** [comment]
https://github.com/timbergeron/QSS-M/commit/e6b88db131e0e6be267a46b9884bea92b99c551b fixes this

**Comment by alexey-lysiuk** [comment]
> [timbergeron@e6b88db](https://github.com/timbergeron/QSS-M/commit/e6b88db131e0e6be267a46b9884bea92b99c551b) fixes this

This fixes problem with Xcode project that I mentioned as an example of incorrect continuous integration statuses.
Two issues with CI itself (the real topic of this report) are still there.

**Comment by alexey-lysiuk** [comment]
[Failed build](https://github.com/Shpoike/Quakespasm/actions/runs/6752032849/job/18356907473) is still marked as succeeded.
```
/Users/runner/work/Quakespasm/Quakespasm/Quake/gl_rlight.c:526:12: error: expected ';' at end of declaration
        float s, w. frac[3];
                  ^
                  ;
/Users/runner/work/Quakespasm/Quakespasm/Quake/gl_rlight.c:533:3: error: use of undeclared identifier 'frac'
                frac[i] = (point[i] - grid->mins[i]) * grid->gridscale[i] - tile[i];
                ^
/Users/runner/work/Quakespasm/Quakespasm/Quake/gl_rlight.c:538:14: error: use of undeclared identifier 'frac'
                w =     ((i&1)?frac[0]:1-frac[0])
                               ^
/Users/runner/work/Quakespasm/Quakespasm/Quake/gl_rlight.c:538:24: error: use of undeclared identifier 'frac'
                w =     ((i&1)?frac[0]:1-frac[0])
                                         ^
/Users/runner/work/Quakespasm/Quakespasm/Quake/gl_rlight.c:539:14: error: use of undeclared identifier 'frac'
                  * ((i&2)?frac[1]:1-frac[1])
                           ^
/Users/runner/work/Quakespasm/Quakespasm/Quake/gl_rlight.c:539:24: error: use of undeclared identifier 'frac'
                  * ((i&2)?frac[1]:1-frac[1])
                                     ^
/Users/runner/work/Quakespasm/Quakespasm/Quake/gl_rlight.c:540:14: error: use of undeclared identifier 'frac'
                  * ((i&4)?frac[2]:1-frac[2]);
                           ^
/Users/runner/work/Quakespasm/Quakespasm/Quake/gl_rlight.c:540:24: error: use of undeclared identifier 'frac'
                  * ((i&4)?frac[2]:1-frac[2]);
                                     ^
```

**Comment by Shpoike** [comment]
There we go. Now reports failures properly.

thanks to the addition of the pmove.c and pmovetst.c files, and the xcode project being a cryptic mess of unreadable hashes I'm going to have to depend on someone rich with an overpriced mac to contribute a merge request or diff or something before it'll start working again.
but yay, now all those nice friendly green ticks are ugly angry red crosses. all is right with the world. :\

**Comment by alexey-lysiuk** [comment]
I made a PR #131 with a fix for Xcode project. Because of CI setup that doesn't build pull requests, [here is a link](https://github.com/alexey-lysiuk/quakespasm-spiked/actions/runs/6760283651) to succeeded build from my fork.

**Comment by Shpoike** [comment]
yup, that got it, thank you.
