### ISSUE TITLE
Broken lighting on re-release E3M3

### ISSUE THREAD

**Issue by MCHDaniel** [Shpoike/Quakespasm#125]
The whole map looks like this. Hasn't happened in any of the previous maps or in the original E3M3.

![spasm0000](https://github.com/Shpoike/Quakespasm/assets/42895292/3c35eb25-2804-4a2d-a15a-241e24428930)

The lighting shows correctly on Quakespasm and Ironwail. Running on Intel Core i5-1035G1, Intel UHD Graphics.

**Comment by tpaulrazvan** [comment]
Can confirm it does happen. Not happening on QS.

**Comment by Shpoike** [comment]
the map has an erroneous _lightmap_scale value of .75 instead of 16/unspecified. This is a texels-per-luxel value which is then treated as if 1, resulting in qss thinking the map was built with an abusively high luxel density.

**Comment by MCHDaniel** [comment]
Great, changing the value in the .bsp does the trick:

![image](https://github.com/Shpoike/Quakespasm/assets/42895292/7c6d5e80-f53e-4ad0-bd13-c203c6cc05fb)

Now it looks as it should:

![spasm0000](https://github.com/Shpoike/Quakespasm/assets/42895292/c182942f-0a7d-4054-8660-0c4ffff60641)
