### ISSUE TITLE
vwep support

### ISSUE THREAD

**Issue by VinnyVicious** [Shpoike/Quakespasm#130]
https://github.com/Shpoike/Quakespasm/blob/06a1f39d438e5bed9d3ddf46828990dbd9f06fb7/Quake/cl_main.c#L1718

**Comment by Shpoike** [comment]
I never liked that mechanism.

Instead, you can use `setattachment(weaponent, playerent, "");` to have some entity follow another. QSS doesn't support specifying a bone to attach it to, but it does still allow it to track the origin of its parent entity without issues.

**Comment by VinnyVicious** [comment]
@Shpoike oh, so it acts like a bone, just not reading from the asset file directly? That's cool.

Is there a debug gizmo that can be enabled in-game to know the correct coords? Like, load player model, load weapon model, then use a gizmo to check the position that should be used in the call?

**Comment by Shpoike** [comment]
<https://quakewiki.org/wiki/DP_GFX_QUAKE3MODELTAGS>
