### ISSUE TITLE
Stop tracking me

### ISSUE THREAD

**Issue by Alevam-Inc** [Shpoike/Quakespasm#134]
after trying to run QSS, my antivirus software said that "Sourceforge.net" was tracking me, so removed it. But even after removing QSS my antivirus software still says I'm being tracked!

**Comment by Shpoike** [comment]
QSS has nothing to do with sourceforge, so whatever that's from its not QSS.

The upstream QS project does(did?) have binaries on sourceforge though, and SF have had a history of inserting malware into installers uploaded to their site. I don't know whether they still do this thanks to past backlash but some of those old installers are likely still around. But again, you won't find any such installer for QSS unless some third-party uploaded it.
