### ISSUE TITLE
engine does not load external vis files

### ISSUE THREAD

**Issue by Nine-H** [Shpoike/Quakespasm#16]
external .lits load fine but transparent water classic maps is not possible without hard patching (which I would rather not).

**Comment by NightFright2k19** [comment]
Seconded. If vis file support was added, one could also use the vis/lit packs made for Mark V.

**Comment by NightFright2k19** [comment]
Someone made a [pull request with .vis support over at vkQuake](https://github.com/Novum/vkQuake/pull/283), maybe the same code can be used here.

**Comment by NightFright2k19** [comment]
[vkQuake added support for this now.](https://github.com/Novum/vkQuake/commit/5bff2903b13bcf58af5a51060b492ade0a49d94b) Any chance to get the same or something similar, then?

**Comment by NightFright2k19** [comment]
Latest Quakespasm 0.94.0 supports it as well.  Now would be a good time.

**Comment by NightFright2k19** [comment]
It looks like latest QSS build from Sep 6, 2021 supports .vis files now. This can be closed. Thanks a lot!
