### ISSUE TITLE
Consider allowing demos without needing `-Fitz`.

### ISSUE THREAD

**Issue by mjr4077au** [Shpoike/Quakespasm#19]
Not asking so much for myself but more on behalf of others. I see so many people running with `-Fitz` just to get the demo reel playing, then ask questions about how to avoid z-fighting in maps, not knowing that passing `-Fitz` stops loading the fixes from the pk3 file that comes with the engine.

I just think it'd be a win for all parties. It seems very preferential to criple the demo reel and think an archivable CVAR to disable demos on execution would be much more preferable.

**Comment by amiga1985** [comment]
All you need to do is, in your autoexec.cfg, put in a line that states,"playdemo demo1"

**Comment by mjr4077au** [comment]
That's playing back demo1, but not the entire reel. That'd also only play back demo1 for whatever game folder I have autoexec.cfg in, not globally. I don't really think it's a solution.

Again it's not so much for me, just a general question on behalf of noobs everywhere.

**Comment by Shpoike** [comment]
cl_demoreel 1
Its in the Extras menu under the name 'Attract Mode'.
