### ISSUE TITLE
[Feature Request] r_drawclipbrushes

### ISSUE THREAD

**Issue by oGkspAz** [Shpoike/Quakespasm#27]
Could we possibly have a command like valve's r_drawclipbrushes to help with developing of maps / levels?
Example: https://wiki.sourceruns.org/wiki/R_drawclipbrushes

**Comment by Shpoike** [comment]
Clip brushes are baked into the bsp. the bsp trees that actually contain those clip brushes have no way to distinguish them from regular walls. This is also why decompiled bsps lack clip brushes too.
So its basically impossible for a Q1 engine to draw this stuff (its a different matter for engines that provide actual brush info, like hl2/q2+ does).
