### ISSUE TITLE
[Feature Request] func_illusionary model scaling support like FTE / DP

### ISSUE THREAD

**Issue by oGkspAz** [Shpoike/Quakespasm#28]
Could we please have support for the scale field in entities like displaying models through func_illusionary?
Example:

FTE
![fte_model](https://user-images.githubusercontent.com/13630539/101239323-4a813f00-36ef-11eb-9a08-57f51e305d99.jpg)

QSS
![qss_model](https://user-images.githubusercontent.com/13630539/101239324-4ce39900-36ef-11eb-80c1-5a3ff4f3c6f8.jpg)

**Comment by eGax** [comment]
This can be closed I believe. @oGkspAz check against the current qss builds because this works for me.

**Comment by Shpoike** [comment]
for now it requires FTE's protocol extensions (which are default-on in QSS).
scale also works with unextended protocol 999, but not for the makestatic builtin. This is consistent with DP and avoids bugs/omissions in QS/forks, hopefully it'll be enabled in a few releases time once QS understands scale properly too.
it will not work with unextended protocol 666.
