### ISSUE TITLE
[Possible Bug] Wrong Zombie spawns in E4M7

### ISSUE THREAD

**Issue by NightFright2k19** [Shpoike/Quakespasm#29]
In E4M7 "Azure Agony", once you enter the first water pool in the start area (with the star-shaped center), some Zombies (at least two on Easy) will spawn after a few seconds. These are supposed to appear underwater, but instead they spawn above the water surface, floating in the air. Tested with latest unmodified QSS x64 build from 2020-10-17.

Might be related to my other [reported issue with lavamen in DoE's R2M3](https://github.com/Shpoike/Quakespasm/issues/26).

*Update*
It seems it's also like that in original DOS Quake. Unsure whether this is intended behavior or not. In my opinion, the Zombies should at least be properly placed on the ground above the pool.

**Comment by mhQuake** [comment]
This happens in vanilla unmodified Win/GL Quake - it's not a QSS bug.

That said, I'm 99.99999999% sure that this is not intended behaviour.  The zombies just need their Z origin to be dropped by 3 units to make them fall properly, and if we consider that info_teleport_destination has `self.origin = self.origin + '0 0 27'` whereas monster_zombie has `$origin	0 0 24` - it seems that the teleport destinations were most likely just positioned wrong in the map.

**Comment by NightFright2k19** [comment]
Not a bug, so...
