### ISSUE TITLE
Bug cl_bob Malice conversion

### ISSUE THREAD

**Issue by Candlemass** [Shpoike/Quakespasm#32]
Setting the flag "cl_bob 0" in the "autoexec.cfg" file for the Malice conversion does nothing.

However, setting it manually in the console works without issue.

Obviously an issue as having to manually set console commands every time you load the game isn't ideal.

Thanks.

**Comment by Candlemass** [comment]
?????????????????????

**Comment by Candlemass** [comment]
Is this abandoned?

**Comment by eGax** [comment]
Setting the flag "cl_bob 0" in "malice/autoexec.cfg" file for me works fine here.

**Comment by Candlemass** [comment]
Okay.

So how do I remove that line of code then to stop this from happening and prevent my flag from being overwritten?

**Comment by garoto** [comment]
`bind w    "+forward ; wait ; cl_bob 0"`

**Comment by Candlemass** [comment]
Appreciate the reply but what file in which PAK is the line located that I need to swap with this one?

What tool do I need to use to make the change?

**Comment by garoto** [comment]
Just add it to your `autoexec.cfg`

**Comment by Candlemass** [comment]
I just copy and pasted your code into the autoexec.cfg file.

There's no change from the default behavior unfortunately...

**Comment by Candlemass** [comment]
I just copy and pasted your code into the autoexec.cfg file.

There's no change from the default behavior unfortunately...

**Comment by Candlemass** [comment]
"Just add it to your autoexec.cfg"

This doesn't do anything?????

**Comment by Candlemass** [comment]
Hello????????

**Comment by Candlemass** [comment]
And this in indeed a bug with quakespasm as I just loaded the game with DarkPlaces with the autoexec file flag set to "cl_bob 0" and it works as intended.

**Comment by Candlemass** [comment]
Get proven wrong. Then go into hiding and not respond.

Looks like accountability isn't a strong trait here instead placing blame on the game rather than the source port.

It's obviously easier to make excuses then actually fix the problem...

**Comment by adelpha** [comment]
@Candlemass

1. Nobody here owes you anything.
2. QSS behaviour is correct. The mod forces cl_bob enabled on map load. That means it will be enabled every time you change level or die and reload. QSS is doing exactly what the mod intends.
3. Garoto told you how to work around it.

Your arrogant and entitled post annoyed me enough that I actually went and dug out my retail Malice disc so I could test it. 

Sure enough, adding the following line to malice/autoexec.cfg solves the problem by applying cl_bob 0 every time you move forward:

`bind w "+forward ; wait ; cl_bob 0"`

If you use another key to move forward, change w to whatever you use.
