### ISSUE TITLE
[bug] moving geo crushes monsters when moving away from them. 

### ISSUE THREAD

**Issue by shamblernaut** [Shpoike/Quakespasm#35]
Instructions to replicate bug, hit button in front of player from save file... might have to wait for a few secs before hitting it for the hell knight to be in a favourable position. Hell knight will get crushed as shutters are moving up away from him. Bug exists in qss 0.93.2, does not exist in qs 0.93.0. occurs regardless of independent physics. 

[quick.sav.zip](https://github.com/Shpoike/Quakespasm/files/6003854/quick.sav.zip)
[bug.dem.zip](https://github.com/Shpoike/Quakespasm/files/6003906/bug.dem.zip)

**Comment by adelpha** [comment]
I've tried to replicate this 20+ times now with that savegame and I cannot get it to happen in latest QSS.

**Comment by neogeographica** [comment]
Might have been fixed by https://github.com/Shpoike/Quakespasm/commit/963bc2e4435df2ed38318c7819eb77097d84e283
