### ISSUE TITLE
[Bug] Arcane Dimensions - no particle trails for grenade/rockets

### ISSUE THREAD

**Issue by pokeshark** [Shpoike/Quakespasm#38]
Issue: Grenades and rockets have no trails with AD 1.80p1
Reproduced with clean install: QSS: Win64 (x86-64) / 2021-April-01 + ad_v1_80p1final.zip + id1/Pak0.pak & Pak1.pak

Notes:
If I use impulse 9 on the AD start map and imediately fire a couple of rockets at the start of current play session, first 2 rockets have trails.. but from the 3rd rocket onwards, the trail disappears.
AD 1.7 impacted as well
Lava/Vore balls have trails as usual, so I think only weapons are impacted.

QSS build:
Git Revision: 1a8fa8713ac40add50ed98ba1b08e1222fc6bedf
Git Date:     2021-04-01
Compile Date: Thu Apr  1 04:13:01 UTC 2021

**Comment by NightFright2k19** [comment]
Might not be a bug, you may have just reached the particle limit. [See my own feature request](https://github.com/Shpoike/Quakespasm/issues/21) to increase the value.

**Comment by pokeshark** [comment]
tested on map start (version from AD 1.8) with clean install
- new build **has the issue**:
Git Revision: 1a8fa8713ac40add50ed98ba1b08e1222fc6bedf
Git Date: 2021-04-01

- old build doesn't have the issue
Git Revision: 9ffca1dedc47061ec4c2b7c230c44aa23a591226
Git Date:     2020-10-17

also used "-particles 8000" as suggested, but it didn't have any impact.

**Comment by adelpha** [comment]
Yeah as far as I can tell there's all kinds of problems with AD in newer QSS builds. I'm just using older ones or vkQuake atm.

**Comment by NightFright2k19** [comment]
It's a minor visual glitch after all, anyway. Nothing that breaks gameplay.

**Comment by bubbleguuum** [comment]
Rockets and grenade never have trails on my system (same versions as OP in first post), not even the 2 first ones.

**Comment by bubbleguuum** [comment]
Also confirming. Thanks for the fix.

**Comment by pokeshark** [comment]
yep, it's fixed with 11-May revision. thanks!

Git Revision: 18c2efc65c5b609a90a0d804c1b8b784f6e764c8
Git Date:     2021-05-11
