### ISSUE TITLE
[Bug] Handling NUM gfx with non-standard width

### ISSUE THREAD

**Issue by NightFright2k19** [Shpoike/Quakespasm#46]
Mods like ["Quake 25 Wolfenstein 3D"](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa0pIZDh3MnZ6b1V6TWM2TThvSjBaX0VMeVFxZ3xBQ3Jtc0tuMDlQT3lLVkpBT3A4UWtaMEZQQngzcHYtWjhyaHJ1bG02d0o2ZmpGOTY0X29QY2VDeTJDQWx4VTNjOU1QNlRQSkhpQ212QWx5MEQzWWJRQTMwSDhmaHVWN0JLWGlnMHctbnhCd0cxUnc4ZnVZbXl5cw&q=https%3A%2F%2Fwww.mediafire.com%2Ffile%2F8zw15ac2p9pho8k%2Fwolf_20210622.zip%2Ffile) won't launch due to a _Draw_PicFromWad: pic "num0" truncated_ error.

This happens since QSS won't accept NUM graphics which are not 24px wide (in the case of this Wolf3D mod, it's 16px). This was already irrelevant in FitzQuake and pretty much any other engine.

**Comment by Shpoike** [comment]
there's apparently a lot of dodgy wad files out there (this has nothing to do with the image dimensions and more to do with the wad header).
QSS has already been made to handle such buggy content less fatally.
