### ISSUE TITLE
[Feature Request] Can we please have the old water distortion :)?

### ISSUE THREAD

**Issue by El-Juancho** [Shpoike/Quakespasm#54]
I remember I talked about this in discord with Shpoike but it seems that he didn't like the idea, honestly, I don't like the normal quakespasm distortion at all and if I remove the distortion I think it looks very very weird.

What if you leave it as an option? I mean, set as default the quakespasm distortion but let the users a cvar that can set the original distortion of the water :)

**Comment by NightFright2k19** [comment]
[There is already a feature request for this](https://github.com/Shpoike/Quakespasm/issues/15), if you bothered to open the second page of the issues tab.

**Comment by garoto** [comment]
Reminder that `Shpoike` doesn't really browse this issue tracker... so, yeah.
