### ISSUE TITLE
[Feature Request] Quake64 bsp support

### ISSUE THREAD

**Issue by xDShot** [Shpoike/Quakespasm#56]
With recent release of remastered Quake came an addon that adds original maps from Quake64, appears to use custom bsp format, maybe straight from original console port. Attempting to run maps from downloaded and extracted q64 mod results in failure:

```
map start 
Warning: Mod_LoadBrushModel: maps/start.bsp has wrong version number (1362506784 should be 29)
Couldn't spawn server maps/start.bsp
```

**Comment by NightFright2k19** [comment]
In general, it would be nice to have support for any content from the new port, including the remastered Dimension of the Past and the new Dimension of the Machine. What needs to be addressed are the localized message strings and the crashes.

**Comment by NightFright2k19** [comment]
Latest QSS from Sep 6 should support this.
