### ISSUE TITLE
EP 6 crashing

### ISSUE THREAD

**Issue by NastyFlytrap** [Shpoike/Quakespasm#58]
The official bethesda source port is out and it came with a new episode.

That episode errors out in QS/QSS

**Comment by NightFright2k19** [comment]
Naturally it does, for it comes with its own progs.dat containing port-specific code, plus the external language stuff. They would probably have to release the source code first before anything can be done about that.

**Comment by DenesHliva** [comment]
So, does that mean we wont be able to play it in other source ports until then?

**Comment by NightFright2k19** [comment]
Latest QSS from Sep 6 has DOTM support. Can be closed.
