### ISSUE TITLE
Original nightmare difficulty

### ISSUE THREAD

**Issue by NastyFlytrap** [Shpoike/Quakespasm#64]
Is there a way for me to turn off this stupid change bethesda did to nightmare? I get that you included it, since bethesda calls the shots and its the 'official' way to play nightmare now, but its stupid and uncalled for. 

Nightmare has been one thing for 25 years and they decide to change it now? No thank you

**Comment by adelpha** [comment]
If you're talking about DoTM then, no. Not unless id/Bethesda release the source code for the progs.dat in that addon, or someone manages to successfully decompile it.

If you're talking about the original episodes, SoA, DoE or DoPA then just use the original versions that are unchanged.

**Comment by Shpoike** [comment]
health limits etc are controlled by the gamecode, not the engine. The engine has absolutely nothing to do with this change.

**Comment by NightFright2k19** [comment]
You can copy the progs.dat files from the Authentic Models Pack into your id1/hipnotic/rogue folders. Besides restoring original Nightmare behavior, it would also fix Megahealth respawning.

**Comment by NastyFlytrap** [comment]
> You can copy the progs.dat files from the Authentic Models Pack into your id1/hipnotic/rogue folders. Besides restoring original Nightmare behavior, it would also fix Megahealth respawning.

Yea.... After i made this topic i figured out that i can just take the pak file apart with winrar and swap the progs.dat file from the original quake to the new one.

Problem is this breaks MG1, which is a damn shame, cause i am sure as hell not playing the official source port

**Comment by NightFright2k19** [comment]
Yes, DOTM right now requires the custom progs.dat which is embedded into its pak0.pak file.

At least the new DOPA version is supported. If you copy AMQ progs.dat from the id1 folder into your DOPA dir, it will override its embedded code.
