### ISSUE TITLE
Request: DDS texture support

### ISSUE THREAD

**Issue by mattreecebentley** [Shpoike/Quakespasm#72]
In my experience working with darkplaces engine, DDS textures load about 4x faster than tga/jpeg/png, largely because they already have their mipmaps precalculated. Given the right [dds encoder](https://github.com/BinomialLLC/crunch), they can also give better quality (via better mipmapping).
Support for this format would be a big win for modders using hd textures.

**Comment by Shpoike** [comment]
Commit 2e1abf9fa7e8d3be06663e57921b316f4ffc3aaa added dds support. Dated 11th April, 2020, one and a half years before your request.
(also include more pixel formats than DP, notably bc6 ufloat, and bc7 unorm.)

**Comment by mattreecebentley** [comment]
Cool. Might want to write that up on the website, as most people, including myself, don't read through old commits on github to see if anythings changed.

**Comment by mushis** [comment]
I second this ^ @Shpoike  :)
