### ISSUE TITLE
[Feature Request] 24bit textures for player.mdl

### ISSUE THREAD

**Issue by timbergeron** [Shpoike/Quakespasm#81]
The only texture that cannot load 24bit images is player.mdl

Either a skin system like Qrack that stays true to the normal shirt top, pant bottom colors or a FTE based baseskin, enemyskin, teamskin

**Comment by Shpoike** [comment]
qss now loads (base)+shirt+underwear textures (and not player specific, eg quakerally's cars or TF's sentries will now be coloured correctly and consistently).

**Comment by timbergeron** [comment]
very cool. thank you, really appreciate it! excited to give it a try
