### ISSUE TITLE
[Bug] Grenade sound buzz on slopes and elevators

### ISSUE THREAD

**Issue by Oplexitie** [Shpoike/Quakespasm#90]
Build :
October 14 2021

Description : 
Placing a grenade on a moving elevator causes a buzzing sound.
This bug also occurs (altho inconsistently) when placing a grenade on a slope.

Steps to replicate :
Enter E1M1 (easiest place to execute this), shoot a grenade on the elevator, wait for the grenade to stop bouncing, then quickly press the button before they explode, and voila.

For the slopes, I couldn't replicate the bug consistently, but I've triggered it multiple times in the start map, in the difficulty selection area, by placing a grenade on the slope leading to the normal difficulty portal.

PS:
I don't know if this is a vanilla quake bug, since almost every source port I've tried has this bug, and I couldn't find any info about it online. But since this bug isn't in Darkplaces, I'm kinda hoping this could also get fixed in QSS.

**Comment by adelpha** [comment]
This is absolutely a vanilla quake "bug", so I'm 99% sure this is "wontfix" as fixing it would deviate from original Quake behaviour.

**Comment by Shpoike** [comment]
Set sv_gameplayfix_bouncedownslopes if you want to match DP's behaviour.
