### ISSUE TITLE
FLAC audio tracks in rogue/music/ are not playing

### ISSUE THREAD

**Issue by mikae1** [Shpoike/Quakespasm#97]
Hi.

I'm running `2021-November-14` build on Manjaro. `lib32-flac 1.3.3-1` and `flac 1.3.3-3` are both installed 

**Expected behavior:**
FLAC audio files in `rogue/music/` [should play](http://quakespasm.sourceforge.net/Quakespasm.html#ss3.1).

**What happens:**
I've tried to encode the CD audio to FLAC for Dissolution of Eternity to `rogue/music/track02.flac` etc. I then get the error message:
> COULDN'T FIND A CDRIP FOR TRACK 5

I've also tried to remux the FLAC stream into an Ogg container (aka [Ogg FLAC](https://www.loc.gov/preservation/digital/formats/fdd/fdd000227.shtml)) using `ffmpeg -i track02.flac -vn -acodec copy track02.ogg` and I then get:
> MUSIC/TRACK05.OGG IS NOT A VALID OGG VORBIS FILE (ERROR -132).
> COULDN'T HANDLE MUSIC FILE MUSIC/TRACK05.OGG

**Comment by Shpoike** [comment]
Quakespasm is strict about music formats and extensions, thus:
ogg vorbis files must be named .ogg
ogg opus files must be named .opus
ogg flac files must be named .flac
despite them all using ogg containers, quakespasm cannot figure out to use a different library to read the relevant files.

so make sure they're ogg-flac files, renamed to a .flac file extension and NOT .ogg nor .oga or whatever other generic extensions there are.
