### ISSUE TITLE
Elevators Wrong Direction in "The Slipgate Massacre" using Bethesda PAK Files

### ISSUE THREAD

**Issue by dtcarpenter** [Shpoike/Quakespasm#98]
Definitely an odd problem. I Downloaded and played a new map ["The Slipgate Massacre"](https://www.quaddicted.com/reviews/e1m1rt23.html) and found that all of the elevators went in the wrong direction - up instead of down and down instead of up. There were no other issues with the level that I could detect. However, I was using the ID1 PAK files from the Bethesda Quake remaster (for the new models) and, as soon as I swapped back the original ID1 PAK files, the problem disappeared.

I also tried the vanilla QuakeSpasm and vkQuake, and experienced the same problem, so it probably originates in the base QuakeSpasm code. Let me know if you recommend also reporting this error on the QuakeSpasm SourceForge site. Thanks.

**Comment by Shpoike** [comment]
I believe this is an issue with the rerelease's gamecode, rather than anything engine-side.
It looks like update 4 fixes SetMoveDir to no longer misinterpret angles_x so I'm just gonna close this.
